import Head from "next/head";
import { useEffect, useState } from "react";
import io from "socket.io-client";

export default function Home() {
  const socket = io("https://bitcoin-checker.onrender.com");
  const [price, setPrice] = useState("");

  useEffect(() => {
    socket.on("connect", () => {
      console.log("connected to wss");
    });

    socket.on("price", (arg) => {
      console.log(arg);
      const massagedArg = Intl.NumberFormat("en-US").format(arg)
      setPrice(massagedArg);
    });
  }, []);



  return (
    <>
      <Head>
        <title>Bitcoin Price Checker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#4c6191] to-[#13336d]">
        <h1 className="text-slate-300">Bitcoin Price Checker</h1>
        <div className="flex  flex-col items-center justify-center h-32 w-96	rounded-xl bg-slate-400">
          <div className="text-orange-700 font-mono font text-xl">{`$${price} USD`}</div>
        </div>
      </main>
    </>
  );
}
